# Generated by Django 5.2.6 on 2025-09-13 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('previous_units', models.IntegerField()),
                ('current_units', models.IntegerField()),
                ('electricity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid')], default='Unpaid', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='room.room')),
            ],
        ),
    ]
