# Generated by Django 5.2.6 on 2025-09-13 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_paymenthistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=15)),
                ("move_in_date", models.DateField()),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="tenant_documents/"
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant",
                        to="room.room",
                    ),
                ),
            ],
        ),
    ]
