# Generated by Django 5.2.6 on 2025-09-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0003_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="month",
            field=models.CharField(max_length=50),
        ),
    ]
