# Generated by Django 5.2.6 on 2025-09-25 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_tenant_electricity_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
