# Generated by Django 5.2.6 on 2025-09-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0009_paymenthistory_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="document",
        ),
        migrations.CreateModel(
            name="TenantDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="tenant_documents/")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="room.tenant",
                    ),
                ),
            ],
        ),
    ]
