# Generated by Django 5.2.6 on 2025-10-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0016_alter_paymentreceived_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="initial_unit",
            field=models.IntegerField(default=0),
        ),
    ]
