# Generated by Django 5.2.6 on 2025-10-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_tenant_initial_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='initial_unit',
            field=models.IntegerField(default=0),
        ),
    ]
