# Generated by Django 5.2.6 on 2025-10-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_paymenthistory_initial_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='initial_unit',
        ),
    ]
