# Generated by Django 5.2.6 on 2025-10-31 09:09

import room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0019_remove_paymenthistory_initial_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="billing_month",
            field=models.CharField(
                default=room.models.current_billing_month, max_length=50
            ),
        ),
    ]
