# Generated by Django 5.2.6 on 2025-10-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0020_alter_paymenthistory_billing_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentreceived",
            name="received_date",
            field=models.CharField(max_length=50),
        ),
    ]
