# Generated by Django 5.2.6 on 2025-10-31 11:14

import room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0021_alter_paymentreceived_received_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentreceived",
            name="received_date",
            field=models.CharField(default=room.models.current_date_str, max_length=50),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(max_length=50),
        ),
    ]
