# Generated by Django 5.2.6 on 2025-10-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "EMAIL_BACKEND",
                    models.CharField(
                        default="django.core.mail.backends.smtp.EmailBackend",
                        max_length=255,
                    ),
                ),
                (
                    "EMAIL_HOST",
                    models.CharField(default="smtp.gmail.com", max_length=255),
                ),
                ("EMAIL_PORT", models.PositiveIntegerField(default=587)),
                ("EMAIL_USE_TLS", models.BooleanField(default=True)),
                ("EMAIL_HOST_USER", models.EmailField(max_length=254)),
                ("EMAIL_HOST_PASSWORD", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
